
spring:
  application:
    name: stream-helloworld
  cloud:
    stream:
      bindings:
        input:
          destination: message
        output:
          destination: message
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    virtual-host: /fgoc
server:
  port: 8080
